name: game_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^1.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
